// Code generated by protoc-gen-go. DO NOT EDIT.
// source: httpResponse.proto

package httpResponse

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HttpResponse struct {
	StatusCode           int32            `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Header               map[string]*Pair `protobuf:"bytes,2,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body                 string           `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *HttpResponse) Reset()         { *m = HttpResponse{} }
func (m *HttpResponse) String() string { return proto.CompactTextString(m) }
func (*HttpResponse) ProtoMessage()    {}
func (*HttpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_httpResponse_0dc5f720002f03d6, []int{0}
}
func (m *HttpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpResponse.Unmarshal(m, b)
}
func (m *HttpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpResponse.Marshal(b, m, deterministic)
}
func (dst *HttpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpResponse.Merge(dst, src)
}
func (m *HttpResponse) XXX_Size() int {
	return xxx_messageInfo_HttpResponse.Size(m)
}
func (m *HttpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HttpResponse proto.InternalMessageInfo

func (m *HttpResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *HttpResponse) GetHeader() map[string]*Pair {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *HttpResponse) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type Pair struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Values               []string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pair) Reset()         { *m = Pair{} }
func (m *Pair) String() string { return proto.CompactTextString(m) }
func (*Pair) ProtoMessage()    {}
func (*Pair) Descriptor() ([]byte, []int) {
	return fileDescriptor_httpResponse_0dc5f720002f03d6, []int{1}
}
func (m *Pair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pair.Unmarshal(m, b)
}
func (m *Pair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pair.Marshal(b, m, deterministic)
}
func (dst *Pair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pair.Merge(dst, src)
}
func (m *Pair) XXX_Size() int {
	return xxx_messageInfo_Pair.Size(m)
}
func (m *Pair) XXX_DiscardUnknown() {
	xxx_messageInfo_Pair.DiscardUnknown(m)
}

var xxx_messageInfo_Pair proto.InternalMessageInfo

func (m *Pair) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Pair) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

type Wrap struct {
	HttpResponse         *HttpResponse `protobuf:"bytes,1,opt,name=httpResponse,proto3" json:"httpResponse,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Wrap) Reset()         { *m = Wrap{} }
func (m *Wrap) String() string { return proto.CompactTextString(m) }
func (*Wrap) ProtoMessage()    {}
func (*Wrap) Descriptor() ([]byte, []int) {
	return fileDescriptor_httpResponse_0dc5f720002f03d6, []int{2}
}
func (m *Wrap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Wrap.Unmarshal(m, b)
}
func (m *Wrap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Wrap.Marshal(b, m, deterministic)
}
func (dst *Wrap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Wrap.Merge(dst, src)
}
func (m *Wrap) XXX_Size() int {
	return xxx_messageInfo_Wrap.Size(m)
}
func (m *Wrap) XXX_DiscardUnknown() {
	xxx_messageInfo_Wrap.DiscardUnknown(m)
}

var xxx_messageInfo_Wrap proto.InternalMessageInfo

func (m *Wrap) GetHttpResponse() *HttpResponse {
	if m != nil {
		return m.HttpResponse
	}
	return nil
}

func init() {
	proto.RegisterType((*HttpResponse)(nil), "HttpResponse")
	proto.RegisterMapType((map[string]*Pair)(nil), "HttpResponse.HeaderEntry")
	proto.RegisterType((*Pair)(nil), "Pair")
	proto.RegisterType((*Wrap)(nil), "Wrap")
}

func init() { proto.RegisterFile("httpResponse.proto", fileDescriptor_httpResponse_0dc5f720002f03d6) }

var fileDescriptor_httpResponse_0dc5f720002f03d6 = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x3d, 0x4b, 0x04, 0x31,
	0x10, 0x86, 0xc9, 0x7e, 0xc1, 0x4e, 0x4e, 0x90, 0x29, 0x24, 0x2a, 0x48, 0xd8, 0x2a, 0x55, 0xf0,
	0xd6, 0x46, 0xad, 0x04, 0x11, 0xae, 0x94, 0x69, 0xac, 0x73, 0x6c, 0xe0, 0x44, 0xb9, 0x84, 0x24,
	0x27, 0xec, 0x2f, 0xf3, 0xef, 0xc9, 0xc5, 0x2b, 0xb2, 0x70, 0xdd, 0xe4, 0xc9, 0xf3, 0x92, 0xcc,
	0x0b, 0xb8, 0x4b, 0xc9, 0x93, 0x8d, 0xde, 0xed, 0xa3, 0xd5, 0x3e, 0xb8, 0xe4, 0x86, 0x5f, 0x06,
	0xab, 0x4d, 0x81, 0xf1, 0x0e, 0x20, 0x26, 0x93, 0x0e, 0xf1, 0xd5, 0x4d, 0x56, 0x30, 0xc9, 0x54,
	0x4b, 0x05, 0xc1, 0x35, 0x74, 0x3b, 0x6b, 0x26, 0x1b, 0x44, 0x25, 0x6b, 0xc5, 0xc7, 0x6b, 0x5d,
	0xc6, 0xf5, 0x26, 0xdf, 0xbd, 0xed, 0x53, 0x98, 0xe9, 0x24, 0x22, 0x42, 0xb3, 0x75, 0xd3, 0x2c,
	0x6a, 0xc9, 0x54, 0x4f, 0x79, 0xbe, 0x79, 0x01, 0x5e, 0xa8, 0x78, 0x09, 0xf5, 0x97, 0x9d, 0xf3,
	0x73, 0x3d, 0x1d, 0x47, 0xbc, 0x85, 0xf6, 0xc7, 0x7c, 0x1f, 0xac, 0xa8, 0x24, 0x53, 0x7c, 0x6c,
	0xf5, 0xbb, 0xf9, 0x0c, 0xf4, 0xcf, 0x9e, 0xab, 0x47, 0x36, 0xdc, 0x43, 0x73, 0x44, 0x67, 0xa2,
	0x57, 0xd0, 0x65, 0x2d, 0xe6, 0x2f, 0xf6, 0x74, 0x3a, 0x0d, 0x4f, 0xd0, 0x7c, 0x04, 0xe3, 0x71,
	0x0d, 0xab, 0xb2, 0x89, 0x1c, 0xe5, 0xe3, 0xc5, 0x62, 0x11, 0x5a, 0x28, 0xdb, 0x2e, 0xb7, 0xf5,
	0xf0, 0x17, 0x00, 0x00, 0xff, 0xff, 0x31, 0xd0, 0x82, 0xf2, 0x43, 0x01, 0x00, 0x00,
}
