// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example.proto

package Im

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Helloworld struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Str                  string   `protobuf:"bytes,2,opt,name=str,proto3" json:"str,omitempty"`
	Opt                  int32    `protobuf:"varint,3,opt,name=opt,proto3" json:"opt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Helloworld) Reset()         { *m = Helloworld{} }
func (m *Helloworld) String() string { return proto.CompactTextString(m) }
func (*Helloworld) ProtoMessage()    {}
func (*Helloworld) Descriptor() ([]byte, []int) {
	return fileDescriptor_example_e5b80c9405a19c73, []int{0}
}
func (m *Helloworld) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Helloworld.Unmarshal(m, b)
}
func (m *Helloworld) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Helloworld.Marshal(b, m, deterministic)
}
func (dst *Helloworld) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Helloworld.Merge(dst, src)
}
func (m *Helloworld) XXX_Size() int {
	return xxx_messageInfo_Helloworld.Size(m)
}
func (m *Helloworld) XXX_DiscardUnknown() {
	xxx_messageInfo_Helloworld.DiscardUnknown(m)
}

var xxx_messageInfo_Helloworld proto.InternalMessageInfo

func (m *Helloworld) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Helloworld) GetStr() string {
	if m != nil {
		return m.Str
	}
	return ""
}

func (m *Helloworld) GetOpt() int32 {
	if m != nil {
		return m.Opt
	}
	return 0
}

func init() {
	proto.RegisterType((*Helloworld)(nil), "Im.helloworld")
}

func init() { proto.RegisterFile("example.proto", fileDescriptor_example_e5b80c9405a19c73) }

var fileDescriptor_example_e5b80c9405a19c73 = []byte{
	// 105 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xad, 0x48, 0xcc,
	0x2d, 0xc8, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xf2, 0xcc, 0x55, 0x72, 0xe0,
	0xe2, 0xca, 0x48, 0xcd, 0xc9, 0xc9, 0x2f, 0xcf, 0x2f, 0xca, 0x49, 0x11, 0xe2, 0xe3, 0x62, 0xca,
	0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x62, 0xca, 0x4c, 0x11, 0x12, 0xe0, 0x62, 0x2e,
	0x2e, 0x29, 0x92, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0x31, 0x41, 0x22, 0xf9, 0x05, 0x25,
	0x12, 0xcc, 0x60, 0x25, 0x20, 0x66, 0x12, 0x1b, 0xd8, 0x30, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xff, 0x91, 0x40, 0xb1, 0x5d, 0x00, 0x00, 0x00,
}
