// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_d336aa72df291970, []int{0}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Request) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Response struct {
	HttpResponse         *HttpResponse `protobuf:"bytes,1,opt,name=httpResponse,proto3" json:"httpResponse,omitempty"`
	Token                string        `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Exp                  string        `protobuf:"bytes,4,opt,name=exp,proto3" json:"exp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_d336aa72df291970, []int{1}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetHttpResponse() *HttpResponse {
	if m != nil {
		return m.HttpResponse
	}
	return nil
}

func (m *Response) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Response) GetExp() string {
	if m != nil {
		return m.Exp
	}
	return ""
}

type UserName struct {
	HttpResponse         *HttpResponse `protobuf:"bytes,1,opt,name=httpResponse,proto3" json:"httpResponse,omitempty"`
	Message              string        `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Username             string        `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UserName) Reset()         { *m = UserName{} }
func (m *UserName) String() string { return proto.CompactTextString(m) }
func (*UserName) ProtoMessage()    {}
func (*UserName) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_d336aa72df291970, []int{2}
}
func (m *UserName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserName.Unmarshal(m, b)
}
func (m *UserName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserName.Marshal(b, m, deterministic)
}
func (dst *UserName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserName.Merge(dst, src)
}
func (m *UserName) XXX_Size() int {
	return xxx_messageInfo_UserName.Size(m)
}
func (m *UserName) XXX_DiscardUnknown() {
	xxx_messageInfo_UserName.DiscardUnknown(m)
}

var xxx_messageInfo_UserName proto.InternalMessageInfo

func (m *UserName) GetHttpResponse() *HttpResponse {
	if m != nil {
		return m.HttpResponse
	}
	return nil
}

func (m *UserName) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UserName) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type HttpResponse struct {
	StatusCode           int32            `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Header               map[string]*Pair `protobuf:"bytes,2,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body                 string           `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *HttpResponse) Reset()         { *m = HttpResponse{} }
func (m *HttpResponse) String() string { return proto.CompactTextString(m) }
func (*HttpResponse) ProtoMessage()    {}
func (*HttpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_d336aa72df291970, []int{3}
}
func (m *HttpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpResponse.Unmarshal(m, b)
}
func (m *HttpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpResponse.Marshal(b, m, deterministic)
}
func (dst *HttpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpResponse.Merge(dst, src)
}
func (m *HttpResponse) XXX_Size() int {
	return xxx_messageInfo_HttpResponse.Size(m)
}
func (m *HttpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HttpResponse proto.InternalMessageInfo

func (m *HttpResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *HttpResponse) GetHeader() map[string]*Pair {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *HttpResponse) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type Pair struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Values               []string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pair) Reset()         { *m = Pair{} }
func (m *Pair) String() string { return proto.CompactTextString(m) }
func (*Pair) ProtoMessage()    {}
func (*Pair) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_d336aa72df291970, []int{4}
}
func (m *Pair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pair.Unmarshal(m, b)
}
func (m *Pair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pair.Marshal(b, m, deterministic)
}
func (dst *Pair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pair.Merge(dst, src)
}
func (m *Pair) XXX_Size() int {
	return xxx_messageInfo_Pair.Size(m)
}
func (m *Pair) XXX_DiscardUnknown() {
	xxx_messageInfo_Pair.DiscardUnknown(m)
}

var xxx_messageInfo_Pair proto.InternalMessageInfo

func (m *Pair) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Pair) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

type Wrap struct {
	HttpResponse         *HttpResponse `protobuf:"bytes,1,opt,name=httpResponse,proto3" json:"httpResponse,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Wrap) Reset()         { *m = Wrap{} }
func (m *Wrap) String() string { return proto.CompactTextString(m) }
func (*Wrap) ProtoMessage()    {}
func (*Wrap) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_d336aa72df291970, []int{5}
}
func (m *Wrap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Wrap.Unmarshal(m, b)
}
func (m *Wrap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Wrap.Marshal(b, m, deterministic)
}
func (dst *Wrap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Wrap.Merge(dst, src)
}
func (m *Wrap) XXX_Size() int {
	return xxx_messageInfo_Wrap.Size(m)
}
func (m *Wrap) XXX_DiscardUnknown() {
	xxx_messageInfo_Wrap.DiscardUnknown(m)
}

var xxx_messageInfo_Wrap proto.InternalMessageInfo

func (m *Wrap) GetHttpResponse() *HttpResponse {
	if m != nil {
		return m.HttpResponse
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "Request")
	proto.RegisterType((*Response)(nil), "Response")
	proto.RegisterType((*UserName)(nil), "UserName")
	proto.RegisterType((*HttpResponse)(nil), "HttpResponse")
	proto.RegisterMapType((map[string]*Pair)(nil), "HttpResponse.HeaderEntry")
	proto.RegisterType((*Pair)(nil), "Pair")
	proto.RegisterType((*Wrap)(nil), "Wrap")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_user_d336aa72df291970) }

var fileDescriptor_user_d336aa72df291970 = []byte{
	// 343 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x6d, 0x9a, 0xa4, 0x4d, 0x27, 0x15, 0x64, 0x11, 0x89, 0x15, 0xa4, 0x2e, 0x1e, 0x7a, 0x0a,
	0x36, 0x5e, 0xd4, 0x93, 0x22, 0xd2, 0x9e, 0x54, 0x16, 0xc5, 0xf3, 0x96, 0x0c, 0x56, 0x6a, 0xb3,
	0x71, 0x77, 0xa3, 0xf6, 0x97, 0xf9, 0xf7, 0x64, 0x37, 0x49, 0x49, 0xc0, 0x53, 0x6f, 0xf3, 0xde,
	0xbc, 0x9d, 0x8f, 0x7d, 0x03, 0x50, 0x28, 0x94, 0x71, 0x2e, 0x85, 0x16, 0xf4, 0x16, 0xfa, 0x0c,
	0x3f, 0x0b, 0x54, 0x9a, 0x8c, 0x20, 0x30, 0x89, 0x8c, 0xaf, 0x31, 0x72, 0xc6, 0xce, 0x64, 0xc0,
	0xb6, 0xd8, 0xe4, 0x72, 0xae, 0xd4, 0xb7, 0x90, 0x69, 0xd4, 0x2d, 0x73, 0x35, 0xa6, 0x08, 0x01,
	0x43, 0x95, 0x8b, 0x4c, 0x21, 0x99, 0xc2, 0x70, 0xa9, 0x75, 0x5e, 0x63, 0x5b, 0x27, 0x4c, 0xf6,
	0xe2, 0x79, 0x83, 0x64, 0x2d, 0x09, 0x39, 0x00, 0x5f, 0x8b, 0x15, 0x66, 0x91, 0x6b, 0xeb, 0x96,
	0x80, 0xec, 0x83, 0x8b, 0x3f, 0x79, 0xe4, 0x59, 0xce, 0x84, 0x54, 0x41, 0xf0, 0xa2, 0x50, 0x3e,
	0x98, 0x71, 0x76, 0x68, 0x13, 0x41, 0x7f, 0x8d, 0x4a, 0xf1, 0x37, 0xac, 0x16, 0xa8, 0x61, 0x6b,
	0x6f, 0xb7, 0xbd, 0x37, 0xfd, 0x75, 0x60, 0xd8, 0x2c, 0x4a, 0x4e, 0x00, 0x94, 0xe6, 0xba, 0x50,
	0x77, 0x22, 0x2d, 0xfb, 0xfa, 0xac, 0xc1, 0x90, 0x29, 0xf4, 0x96, 0xc8, 0x53, 0x94, 0x51, 0x77,
	0xec, 0x4e, 0xc2, 0xe4, 0xa8, 0x35, 0x53, 0x3c, 0xb7, 0xb9, 0xfb, 0x4c, 0xcb, 0x0d, 0xab, 0x84,
	0x84, 0x80, 0xb7, 0x10, 0xe9, 0xa6, 0xea, 0x6d, 0xe3, 0xd1, 0x0d, 0x84, 0x0d, 0xa9, 0xf9, 0x8d,
	0x15, 0x6e, 0x2a, 0x57, 0x4c, 0x48, 0x8e, 0xc1, 0xff, 0xe2, 0x1f, 0x45, 0xb9, 0x4c, 0x98, 0xf8,
	0xf1, 0x13, 0x7f, 0x97, 0xac, 0xe4, 0xae, 0xbb, 0x97, 0x0e, 0x3d, 0x07, 0xcf, 0x50, 0xff, 0x3c,
	0x3d, 0x84, 0x9e, 0x95, 0x29, 0x3b, 0xe2, 0x80, 0x55, 0x88, 0x5e, 0x81, 0xf7, 0x2a, 0x79, 0xbe,
	0xc3, 0xe7, 0x26, 0x8f, 0xe0, 0x19, 0x6f, 0xc8, 0x29, 0x04, 0x33, 0xd4, 0xcf, 0xd6, 0xc1, 0x20,
	0xae, 0x0e, 0x6b, 0x34, 0x88, 0x6b, 0x21, 0xed, 0x90, 0x33, 0x08, 0x67, 0xa8, 0xb7, 0x4e, 0x36,
	0x55, 0x35, 0x49, 0x3b, 0x8b, 0x9e, 0xbd, 0xce, 0x8b, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc2,
	0x53, 0x61, 0x8a, 0xab, 0x02, 0x00, 0x00,
}
